name: wixoss_vs
description: wixoss record app
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.0
  animations: ^2.0.8
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  provider: ^6.0.5

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
